### ISSUE TITLE
question: declaring fact types ahead of time?

### ISSUE THREAD

**Issue by dmfay** [andbi/evrete#13]
hi! I'm getting started with Evrete and have gotten my first few rules working. Now I'm trying to add a rule which inserts a new type of fact into the context (i.e. one that has not been declared a `@Fact` anywhere or inserted before firing the session) like this:

```java
@Rule
@Where(/* conditions */)
public static void addNewThing(
    final RhsContext ctx, @Fact("$one") final One one, @Fact("$two") final Two two
) {
    ctx.insert(new NewThing(one.a, two.b));
}
```
When the conditions align and the rule runs, Evrete complains that it "can not map type" of NewThing and skips the insert. I can get it to insert by declaring a rule method parameter `@Fact("$newThing") final NewThing nt`, but that doesn't make a ton of semantic sense so I'd rather avoid it if possible. Looking at the Javadoc and source code it seems like I should be able to declare the facticity of NewThings ahead of time, like this:

```java
knowledgeService
    .getTypeResolverProvider()
    .instance(knowledgeService.getClassLoader())
    .declare(NewThing.class);
```

but I get the same behavior: "can not map type for 'org.etc.etc.NewThing', insert operation skipped". How can I declare NewThing up front for the TypeResolver and add instances to the context in-rule?

**Comment by andbi** [comment]
Once you've built your ruleset and obtained a `Knowledge` instance, please try `knowledge.getTypeResolver().declare(NewThing.class)` prior to spawning sessions off that knowledge instance. 

Or, if you want declare arbitrary types from within a rule, you can obtain type resolver directly from RHS context:
`ctx.getRuntime().getTypeResolver().declare(NewThing.class)`

Please let me know if that worked for you. 

The reason why your workaround failed is because you're creating a new instance of type resolver rather than updating an existing one.

**Comment by dmfay** [comment]
> The reason why your workaround failed is because you're creating a new instance of type resolver rather than updating an existing one.

ah, that makes sense.

I tried both your suggestions, but in my tests that exercise the addNewThing rule, I see the same exception pointing to the `ctx.insert` call:

```
java.lang.IllegalStateException: No memory allocated for type id: 5. Probable cause: the type has never been mentioned in any LHS.

	at org.evrete.runtime.SessionMemory.get(SessionMemory.java:70)
	at org.evrete.runtime.SessionMemory.get(SessionMemory.java:52)
	at org.evrete.runtime.AbstractRuleSession.insertAtomic(AbstractRuleSession.java:358)
	at org.evrete.runtime.AbstractRuleSession.insertAtomic(AbstractRuleSession.java:352)
	at org.evrete.runtime.AbstractRuleSession.bufferInsert(AbstractRuleSession.java:296)
	at org.evrete.runtime.RuntimeRuleImpl$RhsContextImpl.insert(RuntimeRuleImpl.java:275)
	at org.evrete.api.RhsContext.insert(RhsContext.java:19)
	at org.etc.etc.MyService$Ruleset.addNewThing(MyService.java:61)
```

Here's my Knowledge/Session code, in a static service method (knowledgeService is a static member and Ruleset is a nested static class in the service):

```java
final Knowledge knowledge = knowledgeService.newKnowledge("JAVA-CLASS", MyService.Ruleset.class);

knowledge.getTypeResolver().declare(NewThing.class);

final StatefulSession session = knowledge.newStatefulSession();

....

session.fire();
```

**Comment by andbi** [comment]
I'll look into it. Please stick to the workaround you mentioned, or create a dummy empty rule with the type in question in its LHS.

Btw, if you don't mind me asking, what's the purpose of inserting a fact that will never be queried by the rule engine? If it's about using the engine's memory as a container for arbitrary objects, then you could just declare a Map inside your ruleset and access it from rule  actions/methods.

**Comment by dmfay** [comment]
Thanks! As for the fact type, right now it's part of the rule system's output, along with a bunch of other facts, so I wanted to treat it consistently. Later on too there's a good chance I'll have rules that do query it, I'm still very early in developing the rulesets.

**Comment by andbi** [comment]
I'm afraid that's not possible, and here is why. In Evrete, there is no such thing as single "plain" memory for a specific type. Type memory is always split into buckets. And alpha conditions determine the amount and structure of these buckets. 

For example, if your ruleset contained `"$type.i > 0"` and `"$type.y == 2"` somewhere across your rules, the engine would create four buckets for all possible outcomes (very much like in binary trees). The absence of explicit alpha conditions means an "always true" alpha condition. 

When a new fact is inserted, and its type is resolved, the engine evaluates all the alpha conditions and chooses the destination bucket. In your case, there are no alpha conditions at all, not even the "always true" one, hence the exception. 

I would recommend creating "stub" rules for the types you're planning to deal with later. A simple rule without any conditions or actions will suffice.:

```java
@Rule
public static void ruleStub1(NewThing obj) {
  // Empty method body or development output
}

```
As the type isn't referenced in any conditions, the `@Fact` annotation can be omitted. If you don't want to these stubs during the development, declare them in a super-class or in a stand-alone class:


```java
final Knowledge knowledge = knowledgeService.newKnowledge("JAVA-CLASS", MyService.Ruleset.class, TempRuleStubs.class);

```

**Comment by dmfay** [comment]
If I understand correctly the alpha conditions are the set of possible values/predicates for each given fact class? It does make sense that the engine wouldn't know what to do when there's literally nothing _for_ it to do with a new fact class. Thanks for the explanation!

Is the evrete.org source public? There've been a few corners of it that I've had to put in some effort to figure out so I'd be interested in adding more detail to the documentation later on.

**Comment by andbi** [comment]
Yes, you're right, the [RETE wiki](https://en.wikipedia.org/wiki/Rete_algorithm) refers to them  as to "alpha network".

The library is published under the permissive MIT license, which effectively means no restrictions. And everyone is welcome to contribute!
